name: flutter_avatar
description: Various ready to use Avatars in your Flutter apps
version: 0.1.0
author: timilehinjegede.timothy@gmail.com
homepage: https://github.com/timilehinjegede/flutter-avatar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
